# Generated by Django 4.1.2 on 2022-10-26 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('type_document', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('id_rol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.rols')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
