# Generated by Django 4.1.2 on 2022-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employess',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
